branch-defaults:
  default:
    environment: Omaewamoe-env
environment-defaults:
  Omaewamoe-env:
    branch: null
    repository: null
global:
  application_name: omaewamoe
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
deploy:
  artifact: www/Archive.zip