version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0
  node: circleci/node@5.0.1
  aws: circleci/aws-s3@3.0
  awscli: circleci/aws-cli@2.1.0
jobs:
  backend:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - awscli/install
      - awscli/setup:
          profile-name: eb-cli
      - eb/setup
      - run:
          name: install backend
          command: npm run backend:install
      - run :
          name: build backend
          command: npm run backend:build
      - run:
          name: clear the bucket
          command: aws s3 rm s3://elasticbeanstalk-eu-west-3-436411433992 --recursive
      - run:
          name: deploy to eb
          command: |
            cd udagram-api 
            eb use Omaewamoe-env --profile eb-cli
            eb deploy --profile eb-cli
  frontend:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: prepare frontend
          command: |
            npm run frontend:install
            npm run frontend:build
      - aws/copy:
            arguments: |
              --acl public-read \
              --recursive
            aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
            aws-secret-access-key: AWS_SECRET_ACCESS_KEY_BLUE
            aws-region: AWS_REGION_BLUE
            from : ./udagram-frontend/www
            to : 's3://omaewamoe1'
        
workflows:
  deploy-example:
    jobs:
      - backend
      - frontend