version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0
  node: circleci/node@5.0.1
  aws: circleci/aws-s3@3.0
  awscli: circleci/aws-cli@2.1.0
jobs:
  backend:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - awscli/setup:
          profile-name: eb-cli
      - eb/setup
      - run:
          name: install backend
          command: npm run backend:install
      - run :
          name: build backend
          command: npm run backend:build
      - run:
          name: deploy to eb
          command: |
            cd udagram-api 
            eb use Omaewamoe-env --profile eb-cli
            eb deploy --profile eb-cli
            eb setenv PORT=$PORT POSTGRES_DB=$POSTGRES_DB POSTGRES_HOST=$POSTGRES_HOST POSTGRES_PASSWORD=$POSTGRES_PASSWORD POSTGRES_USERNAME=$POSTGRES_USERNAME URL=$URL AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_BUCKET=$AWS_BUCKET AWS_PROFILE=$AWS_PROFILE AWS_REGION=$AWS_REGION AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY JWT_SECRET=$JWT_SECRET
  frontend:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - awscli/setup:
          profile-name: default
      - run:
          name: prepare frontend
          command: |
            npm run frontend:install
            npm run frontend:build
      - aws/copy:
            arguments: |
              --acl public-read \
              --recursive
            aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
            aws-secret-access-key: AWS_SECRET_ACCESS_KEY_BLUE
            aws-region: AWS_REGION_BLUE
            from : ./udagram-frontend/www
            to : 's3://omaewamoe1'
        
workflows:
  deploy-example:
    jobs:
      - backend:
          filters:
            branches:
              only: main
      - frontend:
          filters:
            branches:
              only: main