version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0
  node: circleci/node@5.0.1
jobs:
  backend:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - eb/setup
      - run:
          name: install backend
          command: npm run backend:install
      - run :
          name: build backend
          command: npm run backend:build
      - run:
          name: deploy to eb
          command: cd udagram-api && eb use Omaewamoe-env && eb deploy Omaewamoe-env
workflows:
  deploy-example:
    jobs:
      - backend