version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0
  node: circleci/node@5.0.1
jobs:
  backend:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - eb/setup
      - run:
          name: install backend
          command: npm run backend:install
      - run :
          name: build backend
          command: npm run backend:build
      - run:
          command: |
            mkdir ~/.aws
            touch ~/.aws/config
            chmod 600 ~/.aws/config
            echo "[profile eb-cli]" > ~/.aws/config
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
      - run:
          name: deploy to eb
          command: |
            cd udagram-api 
            eb use Omaewamoe-env --profile eb-cli
            eb deploy --profile eb-cli
workflows:
  deploy-example:
    jobs:
      - backend